/* tslint:disable:max-line-length */
import { Pipe, PipeTransform } from '@angular/core';

export const CLASSES = [
  {
    id: '/Game/PlayerCharacters/Operative/PlayerClassId_Operative.PlayerClassId_Operative',
    label: 'Zane | Operative',
  },
  {
    id: '/Game/PlayerCharacters/SirenBrawler/PlayerClassId_Siren.PlayerClassId_Siren',
    label: 'Amara | Siren',
  },
  {
    id: '/Game/PlayerCharacters/Beastmaster/PlayerClassId_Beastmaster.PlayerClassId_Beastmaster',
    label: 'FL4K | Beastmaster',
  },
  {
    id: '/Game/PlayerCharacters/Gunner/PlayerClassId_Gunner.PlayerClassId_Gunner',
    label: 'Moze | Gunner',
  },
];

export const BALANCE_BLACKLIST = [
  'EchoLog',
  'RoomDecoration',
  'Enemies',
  'Vehicles',
  'Pickups',
  'WeaponSkin',
  'WeaponTrinket',
  'CustomSkin',
  'CustomHead',
  'NPC_Weapons',
  '_ForAI',
  'RoomDeco',
  'CustomEmote',
  '/Developers/',
  'DigiClone',
  '/Automation/',
  'ECHOTheme',
  '/Missions/',
  '/Maps/',
  '_TEST',
  '/Abilities/',
  '/PlayerCharacters/',
  'EchoTheme',
  'CrazyEarlDefault',
  '_ARCHIVED',
  '/NonPlayerCharacters/',
  '/DA_MadMoxxiDrinkEvent',
  '/PartSets/',
  'TEMP/',
];

export const MANUFACTURER_BLACKLIST = [
  '/Vehicles/',
  '/Enemies/',
  'Ammo',
  'NoManufacturer',
  'Emote',
  'CrewQuarters',
  'SDU',
  'EchoSkin',
  'WeaponTrinket',
  'WeaponSkin',
  'PlayerHead',
  'PlayerSkin',
  'Health',
  'Currency',
  'AI_Custom',
  'Mission',
];

export const INV_DATA_BLACKLIST = [
  'EchoLog',
  'RoomDeco',
  '/Enemies/',
  '/PartSets/',
  '/Pickups/',
  '/Vehicles/',
  '/CustomSkin',
  '/CustomHead',
  '/WeaponSkin',
  '/WeaponTrinket',
  '/CustomEmote',
  '/ECHOTheme',
  '/Booster/',
  '/Mission',
  '/NonPlayerCharacters/',
  '/Abilities/',
  '/Maps/',
  'EchoTheme',
  '/Streaming/',
  '/EchoDevice/'
];

export function bestGuessManufacturer(balance: string, manufacturer: string) {
  const manGuess = MANUFACTURER_MAPPINGS.filter(f => f.keys.some(k => balance.includes(k)));
  if (manGuess.length > 0) {
    return manGuess[0].manufacturer;
  }
  return manufacturer;
}

export function filterBlacklist(d: string[], b: string[]): string[] {
  return d.filter(di => !b.some(bi => di.includes(bi)));
}

export const MANUFACTURER_MAPPINGS = [
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Dahl.Dahl',
    keys: ['DAHL', 'DAL'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Vladof.Vladof',
    keys: ['Vladof', 'VLA'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Torgue.Torgue',
    keys: ['Torgue', 'TOR'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Maliwan.Maliwan',
    keys: ['MAL'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Tediore.Tediore',
    keys: ['Tediore', 'TED'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/CoV.CoV',
    keys: ['COV'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Eridian.Eridian',
    keys: ['Fabricator'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Atlas.Atlas',
    keys: ['Atlas', 'ATL'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Jakobs.Jakobs',
    keys: ['JAK'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Hyperion.Hyperion',
    keys: ['Hyperion', 'HYP'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Pangolin.Pangolin',
    keys: ['Pangolin', 'PAN'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Anshin.Anshin',
    keys: ['Anshin'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/ClassMod.ClassMod',
    keys: ['ClassMod'],
  },
  {
    manufacturer: '/Game/Gear/Manufacturers/_Design/Eridian_NoMinGamestage.Eridian_NoMinGamestage',
    keys: ['Artifact'],
  },
];

export const PETS = [];

export const CURRENCIES = {
  money: 618814354,
  eridium: 3679636065,
};

export const INVENTORY_SLOTS = [];

export const SDUS = [];
export const AMMO = [];
export const CHALLENGES = [];

export const maxLevel = 65;
export const expValues = [
  0,          // lvl 1
  358,        // lvl 2
  1241,       // lvl 3
  2850,       // lvl 4
  5376,       // lvl 5
  8997,       // lvl 6
  13886,      // lvl 7
  20208,      // lvl 8
  28126,      // lvl 9
  37798,      // lvl 10
  49377,      // lvl 11
  63016,      // lvl 12
  78861,      // lvl 13
  97061,      // lvl 14
  117757,     // lvl 15
  141092,     // lvl 16
  167206,     // lvl 17
  196238,     // lvl 18
  228322,     // lvl 19
  263595,     // lvl 20
  302190,     // lvl 21
  344238,     // lvl 22
  389873,     // lvl 23
  439222,     // lvl 24
  492414,     // lvl 25
  549578,     // lvl 26
  610840,     // lvl 27
  676325,     // lvl 28
  746158,     // lvl 29
  820463,     // lvl 30
  899363,     // lvl 31
  982980,     // lvl 32
  1071435,    // lvl 33
  1164850,    // lvl 34
  1263343,    // lvl 35
  1367034,    // lvl 36
  1476041,    // lvl 37
  1590483,    // lvl 38
  1710476,    // lvl 39
  1836137,    // lvl 40
  1967582,    // lvl 41
  2104926,    // lvl 42
  2248285,    // lvl 43
  2397772,    // lvl 44
  2553501,    // lvl 45
  2715586,    // lvl 46
  2884139,    // lvl 47
  3059273,    // lvl 48
  3241098,    // lvl 49
  3429728,    // lvl 50
  3625271,    // lvl 51
  3827840,    // lvl 52
  4037543,    // lvl 53
  4254491,    // lvl 54
  4478792,    // lvl 55
  4710556,    // lvl 56
  4949890,    // lvl 57
  5196902,    // lvl 58
  5451701,    // lvl 59
  5714393,    // lvl 60
  5985086,    // lvl 61
  6263885,    // lvl 62
  6550897,    // lvl 63
  6846227,    // lvl 64
  7149982,    // lvl 65
  7462266,    // lvl 66
  7783184,    // lvl 67
  8112840,    // lvl 68
  8451340,    // lvl 69
  8798786,    // lvl 70
  9155282,    // lvl 71
  9520931,    // lvl 72
  9895837,    // lvl 73
  10280103,    // lvl 74
  10673830,    // lvl 75
  11077120,    // lvl 76
  11490077,    // lvl 77
  11912801,    // lvl 78
  12345393,    // lvl 79
  12787955,    // lvl 80
];

export const CUSTOMIZATIONS = [
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_Default.CustomHead_Beastmaster_Default',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_Default.CustomSkin_Beastmaster_Default',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_02_Cheer.CustomEmote_Beastmaster_02_Cheer',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_04_Laugh.CustomEmote_Beastmaster_04_Laugh',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_03_Point.CustomEmote_Beastmaster_03_Point',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_01_Wave.CustomEmote_Beastmaster_01_Wave',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_Default.CustomHead_Gunner_Default',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_Default.CustomSkin_Gunner_Default',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_02_Cheer.CustomEmote_Gunner_02_Cheer',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_04_Laugh.CustomEmote_Gunner_04_Laugh',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_03_Point.CustomEmote_Gunner_03_Point',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_01_Wave.CustomEmote_Gunner_01_Wave',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_Default.CustomHead_Operative_Default',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_Default.CustomSkin_Operative_Default',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_02_Cheer.CustomEmote_Operative_02_Cheer',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_04_Laugh.CustomEmote_Operative_04_Laugh',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_03_Point.CustomEmote_Operative_03_Point',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_01_Wave.CustomEmote_Operative_01_Wave',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_Default.CustomHead_Siren_Default',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_Default.CustomSkin_Siren_Default',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_02_Cheer.CustomEmote_Siren_02_Cheer',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_04_Laugh.CustomEmote_Siren_04_Laugh',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_03_Point.CustomEmote_Siren_03_Point',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_01_Wave.CustomEmote_Siren_01_Wave',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_Default.ECHOTheme_Default',
  '/Game/PatchDLC/Raid1/Customizations/RoomDeco/RoomDeco_Raid1_1.RoomDeco_Raid1_1',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_21.CustomHead_Siren_21',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_36.CustomSkin_Siren_36',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_5.CustomHead_Siren_5',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_15.CustomSkin_Siren_15',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_06.ECHOTheme_06',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_23.CustomHead_Siren_23',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_20.CustomHead_Siren_20',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_41.CustomSkin_Siren_41',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_41.CustomSkin_Gunner_41',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_26.CustomHead_Siren_26',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_41.CustomSkin_Operative_41',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_26.CustomHead_Operative_26',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_11.CustomSkin_Siren_11',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_17.CustomHead_Siren_17',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_4.CustomSkin_Siren_4',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_24.CustomHead_Siren_24',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_29.CustomSkin_Siren_29',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_27.CustomSkin_Siren_27',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_23.ECHOTheme_23',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_7.CustomHead_Siren_7',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_9.CustomHead_Siren_9',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_10.CustomHead_Siren_10',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_11.CustomHead_Siren_11',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_12.CustomHead_Siren_12',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_13.CustomHead_Siren_13',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_14.CustomHead_Siren_14',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_16.CustomHead_Siren_16',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_18.CustomHead_Siren_18',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_19.CustomHead_Siren_19',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_5.CustomSkin_Siren_5',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_7.CustomSkin_Siren_7',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_8.CustomSkin_Siren_8',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_9.CustomSkin_Siren_9',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_10.CustomSkin_Siren_10',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_13.CustomSkin_Siren_13',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_14.CustomSkin_Siren_14',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_18.CustomSkin_Siren_18',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_39.CustomSkin_Siren_39',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_05_Heart.CustomEmote_Siren_05_Heart',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_06_FingerGuns.CustomEmote_Siren_06_FingerGuns',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_09_RobotDance.CustomEmote_Siren_09_RobotDance',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_10_KickDance.CustomEmote_Siren_10_KickDance',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_11_ChickenDance.CustomEmote_Siren_11_ChickenDance',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Emotes/CustomEmote_Siren_12_Death.CustomEmote_Siren_12_Death',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_01.ECHOTheme_01',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_02.ECHOTheme_02',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_03.ECHOTheme_03',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_04.ECHOTheme_04',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_05.ECHOTheme_05',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_08.ECHOTheme_08',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_09.ECHOTheme_09',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_10.ECHOTheme_10',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_26.ECHOTheme_26',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_27.ECHOTheme_27',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_28.ECHOTheme_28',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_29.ECHOTheme_29',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_30.ECHOTheme_30',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_8.CustomHead_Beastmaster_8',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_17.CustomHead_Beastmaster_17',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_17.CustomSkin_Siren_17',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_12.CustomSkin_Siren_12',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_28.CustomSkin_Siren_28',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_19.CustomSkin_Siren_19',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_17.CustomHead_Gunner_17',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_26.CustomSkin_Beastmaster_26',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_27.CustomSkin_Gunner_27',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_6.CustomHead_Beastmaster_6',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_3.CustomSkin_Siren_3',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_28.CustomSkin_Gunner_28',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_2.CustomSkin_Siren_2',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_8.CustomHead_Siren_8',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_24.ECHOTheme_24',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_16.CustomSkin_Siren_16',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_21.ECHOTheme_21',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_20.ECHOTheme_20',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_1.CustomHead_Siren_1',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_12.CustomSkin_Operative_12',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_17.CustomSkin_Operative_17',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_16.CustomSkin_Operative_16',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_6.CustomSkin_Siren_6',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_33.ECHOTheme_33',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_28.CustomSkin_Beastmaster_28',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_27.CustomSkin_Beastmaster_27',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_6.CustomSkin_Gunner_6',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_25.CustomSkin_Gunner_25',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_6.CustomHead_Siren_6',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_41.CustomSkin_Beastmaster_41',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_14.ECHOTheme_14',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_25.CustomSkin_Siren_25',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_34.ECHOTheme_34',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_15.CustomHead_Siren_15',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_17.CustomHead_Operative_17',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_20.CustomSkin_Siren_20',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_20.CustomSkin_Gunner_20',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_4.CustomHead_Beastmaster_4',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_22.ECHOTheme_22',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_18.ECHOTheme_18',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_26.CustomHead_Gunner_26',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_12.CustomSkin_Gunner_12',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_17.CustomSkin_Gunner_17',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_16.CustomSkin_Gunner_16',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_15.CustomHead_Beastmaster_15',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_4.CustomHead_Siren_4',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_1.CustomSkin_Siren_1',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_12.CustomSkin_Beastmaster_12',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_17.CustomSkin_Beastmaster_17',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_16.CustomSkin_Beastmaster_16',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_36.CustomSkin_Beastmaster_36',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_26.CustomSkin_Siren_26',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_28.CustomSkin_Operative_28',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_07.ECHOTheme_07',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_4.CustomHead_Operative_4',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_7.CustomHead_Beastmaster_7',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_9.CustomHead_Beastmaster_9',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_10.CustomHead_Beastmaster_10',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_11.CustomHead_Beastmaster_11',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_12.CustomHead_Beastmaster_12',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_13.CustomHead_Beastmaster_13',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_14.CustomHead_Beastmaster_14',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_16.CustomHead_Beastmaster_16',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_18.CustomHead_Beastmaster_18',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_19.CustomHead_Beastmaster_19',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_5.CustomSkin_Beastmaster_5',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_7.CustomSkin_Beastmaster_7',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_8.CustomSkin_Beastmaster_8',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_9.CustomSkin_Beastmaster_9',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_10.CustomSkin_Beastmaster_10',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_11.CustomSkin_Beastmaster_11',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_13.CustomSkin_Beastmaster_13',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_14.CustomSkin_Beastmaster_14',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_15.CustomSkin_Beastmaster_15',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_18.CustomSkin_Beastmaster_18',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_39.CustomSkin_Beastmaster_39',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_05_Heart.CustomEmote_Beastmaster_05_Heart',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_06_FingerGuns.CustomEmote_Beastmaster_06_FingerGuns',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_09_RobotDance.CustomEmote_Beastmaster_09_RobotDance',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_10_KickDance.CustomEmote_Beastmaster_10_KickDance',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_11_Chicken_Dance.CustomEmote_Beastmaster_11_Chicken_Dance',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Emotes/CustomEmote_Beastmaster_12_Death.CustomEmote_Beastmaster_12_Death',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_5.CustomSkin_Gunner_5',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_7.CustomSkin_Gunner_7',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_8.CustomSkin_Gunner_8',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_9.CustomSkin_Gunner_9',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_10.CustomSkin_Gunner_10',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_11.CustomSkin_Gunner_11',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_13.CustomSkin_Gunner_13',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_14.CustomSkin_Gunner_14',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_15.CustomSkin_Gunner_15',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_18.CustomSkin_Gunner_18',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_39.CustomSkin_Gunner_39',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_7.CustomHead_Gunner_7',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_9.CustomHead_Gunner_9',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_10.CustomHead_Gunner_10',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_11.CustomHead_Gunner_11',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_12.CustomHead_Gunner_12',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_13.CustomHead_Gunner_13',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_14.CustomHead_Gunner_14',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_16.CustomHead_Gunner_16',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_18.CustomHead_Gunner_18',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_19.CustomHead_Gunner_19',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_05_Heart.CustomEmote_Gunner_05_Heart',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_06_FingerGuns.CustomEmote_Gunner_06_FingerGuns',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_09_RobotDance.CustomEmote_Gunner_09_RobotDance',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_10_KickDance.CustomEmote_Gunner_10_KickDance',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_11_ChickenDance.CustomEmote_Gunner_11_ChickenDance',
  '/Game/PlayerCharacters/_Customizations/Gunner/Emotes/CustomEmote_Gunner_12_Death.CustomEmote_Gunner_12_Death',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_19.ECHOTheme_19',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_21.CustomSkin_Siren_21',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_31.ECHOTheme_31',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_25.CustomSkin_Operative_25',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_6.CustomSkin_Beastmaster_6',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_1.CustomSkin_Gunner_1',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_21.CustomSkin_Operative_21',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_15.CustomHead_Gunner_15',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_15.CustomHead_Operative_15',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_8.CustomHead_Operative_8',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_6.CustomHead_Operative_6',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_1.CustomHead_Operative_1',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_8.CustomHead_Gunner_8',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_1.CustomHead_Gunner_1',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_6.CustomHead_Gunner_6',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_4.CustomHead_Gunner_4',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_1.CustomHead_Beastmaster_1',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_21.CustomSkin_Beastmaster_21',
  '/Game/PatchDLC/BloodyHarvest/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_11.ECHOTheme_11',
  '/Game/PatchDLC/BloodyHarvest/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_40.CustomSkin_Beastmaster_40',
  '/Game/PatchDLC/BloodyHarvest/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_40.CustomSkin_Gunner_40',
  '/Game/PatchDLC/BloodyHarvest/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_40.CustomSkin_Operative_40',
  '/Game/PatchDLC/BloodyHarvest/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_40.CustomSkin_Siren_40',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_25.CustomHead_Beastmaster_25',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_25.CustomHead_Gunner_25',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_25.CustomHead_Operative_25',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_25.CustomHead_Siren_25',
  '/Game/PatchDLC/Raid1/PlayerCharacters/_Customizations/Beastmaster/CustomSkin_Beastmaster_45.CustomSkin_Beastmaster_45',
  '/Game/PatchDLC/Raid1/PlayerCharacters/_Customizations/Gunner/CustomSkin_Gunner_45.CustomSkin_Gunner_45',
  '/Game/PatchDLC/Raid1/PlayerCharacters/_Customizations/Operative/CustomSkin_Operative_45.CustomSkin_Operative_45',
  '/Game/PatchDLC/Raid1/PlayerCharacters/_Customizations/Siren/CustomSkin_Siren_45.CustomSkin_Siren_45',
  '/Game/PatchDLC/Raid1/Customizations/EchoDevice/ECHOTheme_38.ECHOTheme_38',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_19.CustomSkin_Operative_19',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_64.ECHOTheme_64',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_65.ECHOTheme_65',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomSkin_Beastmaster_46.CustomSkin_Beastmaster_46',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomSkin_Gunner_46.CustomSkin_Gunner_46',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomSkin_Operative_46.CustomSkin_Operative_46',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomSkin_Siren_46.CustomSkin_Siren_46',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_66.ECHOTheme_66',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/Emotes/SirenBrawler/CustomEmote_Siren_14_MakeItRain.CustomEmote_Siren_14_MakeItRain',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/Emotes/Operative/CustomEmote_Operative_14_MakeItRain.CustomEmote_Operative_14_MakeItRain',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_36.ECHOTheme_36',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomSkin_Beastmaster_44.CustomSkin_Beastmaster_44',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomSkin_Operative_44.CustomSkin_Operative_44',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomHead_Siren_30.CustomHead_Siren_30',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomSkin_Siren_44.CustomSkin_Siren_44',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomSkin_Gunner_44.CustomSkin_Gunner_44',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomHead_Beastmaster_30.CustomHead_Beastmaster_30',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomHead_Gunner_30.CustomHead_Gunner_30',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_22.CustomHead_Siren_22',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_30.CustomSkin_Siren_30',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_31.CustomSkin_Siren_31',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_32.CustomSkin_Siren_32',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/ECHODevice/EchoTheme_Valentines_01.EchoTheme_Valentines_01',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/CustomSkin_Beastmaster_50.CustomSkin_Beastmaster_50',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/CustomSkin_Gunner_50.CustomSkin_Gunner_50',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/CustomSkin_Operative_50.CustomSkin_Operative_50',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/CustomSkin_Siren_50.CustomSkin_Siren_50',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/Emotes/SirenBrawler/CustomEmote_Siren_13_HandsomeJack.CustomEmote_Siren_13_HandsomeJack',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_7.CustomHead_Operative_7',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_9.CustomHead_Operative_9',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_10.CustomHead_Operative_10',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_11.CustomHead_Operative_11',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_12.CustomHead_Operative_12',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_13.CustomHead_Operative_13',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_14.CustomHead_Operative_14',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_16.CustomHead_Operative_16',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_18.CustomHead_Operative_18',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_19.CustomHead_Operative_19',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_5.CustomSkin_Operative_5',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_7.CustomSkin_Operative_7',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_8.CustomSkin_Operative_8',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_9.CustomSkin_Operative_9',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_10.CustomSkin_Operative_10',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_11.CustomSkin_Operative_11',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_13.CustomSkin_Operative_13',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_14.CustomSkin_Operative_14',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_15.CustomSkin_Operative_15',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_18.CustomSkin_Operative_18',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_39.CustomSkin_Operative_39',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_05_Heart.CustomEmote_Operative_05_Heart',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_06_FingerGuns.CustomEmote_Operative_06_FingerGuns',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_09_RobotDance.CustomEmote_Operative_09_RobotDance',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_10_KickDance.CustomEmote_Operative_10_KickDance',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_11_ChickenDance.CustomEmote_Operative_11_ChickenDance',
  '/Game/PlayerCharacters/_Customizations/Operative/Emotes/CustomEmote_Operative_12_Death.CustomEmote_Operative_12_Death',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_32.ECHOTheme_32',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/Emotes/Operative/CustomEmote_Operative_13_HandsomeJack.CustomEmote_Operative_13_HandsomeJack',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/_Shared/CustomSkin_Siren__DLC2_01.CustomSkin_Siren__DLC2_01',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_DLC2_02.ECHOTheme_DLC2_02',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/_Shared/CustomHead_Gunner_DLC2_01.CustomHead_Gunner_DLC2_01',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/Emotes/Gunner/CustomEmote_Gunner_16.CustomEmote_Gunner_16',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_19.CustomSkin_Gunner_19',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/_Shared/CustomHead_Siren_DLC2_01.CustomHead_Siren_DLC2_01',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/_Shared/CustomSkin_Beastmaster_DLC2_01.CustomSkin_Beastmaster_DLC2_01',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/Emotes/SirenBrawler/CustomEmote_Siren_16.CustomEmote_Siren_16',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_22.CustomHead_Gunner_22',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_30.CustomSkin_Gunner_30',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_31.CustomSkin_Gunner_31',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_32.CustomSkin_Gunner_32',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/Emotes/Gunner/CustomEmote_Gunner_14_MakeItRain.CustomEmote_Gunner_14_MakeItRain',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/Emotes/Beastmaster/CustomEmote_Beastmaster_14_MakeItRain.CustomEmote_Beastmaster_14_MakeItRain',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/Emotes/Beastmaster/CustomEmote_Beastmaster_13_HandsomeJack.CustomEmote_Beastmaster_13_HandsomeJack',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/_Shared/CustomHead_Beastmaster_DLC2_01.CustomHead_Beastmaster_DLC2_01',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/_Shared/CustomHead_Operative_DLC2_01.CustomHead_Operative_DLC2_01',
  '/Game/PatchDLC/CitizenScience/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_CS.CustomSkin_Gunner_CS',
  '/Game/PatchDLC/CitizenScience/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_CS.CustomSkin_Siren_CS',
  '/Game/PatchDLC/CitizenScience/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_CS.CustomHead_Gunner_CS',
  '/Game/PatchDLC/CitizenScience/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_CS.CustomSkin_Operative_CS',
  '/Game/PatchDLC/CitizenScience/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_CS.CustomSkin_Beastmaster_CS',
  '/Game/PatchDLC/CitizenScience/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_CS.CustomHead_Siren_CS',
  '/Game/PatchDLC/CitizenScience/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_CS.CustomHead_Operative_CS',
  '/Game/PatchDLC/CitizenScience/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_CS.CustomHead_Beastmaster_CS',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/_Shared/CustomSkin_Operative__DLC2_01.CustomSkin_Operative__DLC2_01',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_DLC2_03.ECHOTheme_DLC2_03',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_DLC2_04.ECHOTheme_DLC2_04',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/_Shared/CustomSkin_Gunner_DLC2_01.CustomSkin_Gunner_DLC2_01',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/Emotes/SirenBrawler/CustomEmote_Siren_15.CustomEmote_Siren_15',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_DLC2_01.ECHOTheme_DLC2_01',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/_Shared/CustomHead_Operative_30.CustomHead_Operative_30',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_3.CustomSkin_Operative_3',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_2.CustomSkin_Operative_2',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_26.CustomSkin_Gunner_26',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_26.CustomSkin_Operative_26',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_2.CustomSkin_Beastmaster_2',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_2.CustomSkin_Gunner_2',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_4.CustomSkin_Operative_4',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_4.CustomSkin_Gunner_4',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_1.CustomSkin_Operative_1',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_21.CustomSkin_Gunner_21',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_27.CustomSkin_Operative_27',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_6.CustomSkin_Operative_6',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_3.CustomSkin_Beastmaster_3',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_4.CustomSkin_Beastmaster_4',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_27.CustomHead_Operative_27',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_27.CustomHead_Gunner_27',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_27.CustomHead_Beastmaster_27',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_27.CustomHead_Siren_27',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_42.CustomSkin_Operative_42',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_42.CustomSkin_Gunner_42',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_42.CustomSkin_Beastmaster_42',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_42.CustomSkin_Siren_42',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/Emotes/Beastmaster/CustomEmote_Beastmaster_15.CustomEmote_Beastmaster_15',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/Emotes/Beastmaster/CustomEmote_Beastmaster_16.CustomEmote_Beastmaster_16',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/Emotes/Gunner/CustomEmote_Gunner_15.CustomEmote_Gunner_15',
  '/Game/PatchDLC/Dandelion/PlayerCharacters/_Customizations/Emotes/Gunner/CustomEmote_Gunner_13_Handsome_Jack.CustomEmote_Gunner_13_Handsome_Jack',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/Emotes/Operative/CustomEmote_Operative_15.CustomEmote_Operative_15',
  '/Game/PatchDLC/Hibiscus/PlayerCharacters/_Customizations/Emotes/Operative/CustomEmote_Operative_16.CustomEmote_Operative_16',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_26.CustomHead_Beastmaster_26',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_24.CustomHead_Beastmaster_24',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_20.CustomHead_Beastmaster_20',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_5.CustomHead_Beastmaster_5',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_23.CustomHead_Beastmaster_23',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_21.CustomHead_Beastmaster_21',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_22.CustomHead_Beastmaster_22',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/CustomHead_BeastMaster_Twitch.CustomHead_BeastMaster_Twitch',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_29.CustomHead_Beastmaster_29',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_28.CustomHead_Beastmaster_28',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_20.CustomHead_Gunner_20',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_5.CustomHead_Gunner_5',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_23.CustomHead_Gunner_23',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_24.CustomHead_Gunner_24',
  '/Game/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_21.CustomHead_Gunner_21',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/CustomHead_Gunner_Twitch.CustomHead_Gunner_Twitch',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_29.CustomHead_Gunner_29',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_28.CustomHead_Gunner_28',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_20.CustomHead_Operative_20',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_24.CustomHead_Operative_24',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_23.CustomHead_Operative_23',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_21.CustomHead_Operative_21',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_22.CustomHead_Operative_22',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/CustomHead_Operative_Twitch.CustomHead_Operative_Twitch',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_29.CustomHead_Operative_29',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_28.CustomHead_Operative_28',
  '/Game/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_5.CustomHead_Operative_5',
  '/Game/PatchDLC/EventVDay/PlayerCharacters/_Shared/CustomHead_Siren_Twitch.CustomHead_Siren_Twitch',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_29.CustomHead_Siren_29',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_28.CustomHead_Siren_28',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_30.CustomSkin_Beastmaster_30',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_23.CustomSkin_Beastmaster_23',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_29.CustomSkin_Beastmaster_29',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_25.CustomSkin_Beastmaster_25',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_37.CustomSkin_Beastmaster_37',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_19.CustomSkin_Beastmaster_19',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_31.CustomSkin_Beastmaster_31',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_35.CustomSkin_Beastmaster_35',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_1.CustomSkin_Beastmaster_1',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_22.CustomSkin_Beastmaster_22',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_34.CustomSkin_Beastmaster_34',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_43.CustomSkin_Beastmaster_43',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_32.CustomSkin_Beastmaster_32',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_20.CustomSkin_Beastmaster_20',
  '/Game/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_24.CustomSkin_Beastmaster_24',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_23.CustomSkin_Gunner_23',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_29.CustomSkin_Gunner_29',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_37.CustomSkin_Gunner_37',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_35.CustomSkin_Gunner_35',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_22.CustomSkin_Gunner_22',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_36.CustomSkin_Gunner_36',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_34.CustomSkin_Gunner_34',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_43.CustomSkin_Gunner_43',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_3.CustomSkin_Gunner_3',
  '/Game/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_24.CustomSkin_Gunner_24',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_30.CustomSkin_Operative_30',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_23.CustomSkin_Operative_23',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_29.CustomSkin_Operative_29',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_37.CustomSkin_Operative_37',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_31.CustomSkin_Operative_31',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_35.CustomSkin_Operative_35',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_22.CustomSkin_Operative_22',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_36.CustomSkin_Operative_36',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_34.CustomSkin_Operative_34',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_43.CustomSkin_Operative_43',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_32.CustomSkin_Operative_32',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_20.CustomSkin_Operative_20',
  '/Game/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_24.CustomSkin_Operative_24',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_23.CustomSkin_Siren_23',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_37.CustomSkin_Siren_37',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_35.CustomSkin_Siren_35',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_22.CustomSkin_Siren_22',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_34.CustomSkin_Siren_34',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_43.CustomSkin_Siren_43',
  '/Game/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_24.CustomSkin_Siren_24',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_35.ECHOTheme_35',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_12.ECHOTheme_12',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_16.ECHOTheme_16',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_17.ECHOTheme_17',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_15.ECHOTheme_15',
  '/Game/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_13.ECHOTheme_13',
  '/Game/PatchDLC/Customizations/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_37.ECHOTheme_37',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/Operative/Heads/CustomHead_Operative_34.CustomHead_Operative_34',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/Gunner/Heads/CustomHead_Gunner_34.CustomHead_Gunner_34',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/Beastmaster/Heads/CustomHead_Beastmaster_34.CustomHead_Beastmaster_34',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/SirenBrawler/Heads/CustomHead_Siren_34.CustomHead_Siren_34',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/Operative/Skins/CustomSkin_Operative_47.CustomSkin_Operative_47',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/Gunner/Skins/CustomSkin_Gunner_47.CustomSkin_Gunner_47',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/Beastmaster/Skins/CustomSkin_Beastmaster_47.CustomSkin_Beastmaster_47',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/SirenBrawler/Skins/CustomSkin_Siren_47.CustomSkin_Siren_47',
  '/Game/PatchDLC/Event2/PlayerCharacters/_Customizations/EchoDevice/ECHOTheme_44.ECHOTheme_44',
];

export const WEAPON_SKINS = [
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_15.WeaponSkin_15',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_20.WeaponSkin_20',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_1.WeaponSkin_1',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_24.WeaponSkin_24',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_13.WeaponSkin_13',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_17.WeaponSkin_17',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_5.WeaponSkin_5',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_4.WeaponSkin_4',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_16.WeaponSkin_16',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_19.WeaponSkin_19',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_22.WeaponSkin_22',
  '/Game/PatchDLC/BloodyHarvest/Gear/Weapons/WeaponSkins/WeaponSkin_BloodyHarvest_01.WeaponSkin_BloodyHarvest_01',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_21.WeaponSkin_21',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_8.WeaponSkin_8',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_6.WeaponSkin_6',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_10.WeaponSkin_10',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_11.WeaponSkin_11',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_9.WeaponSkin_9',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_18.WeaponSkin_18',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_12.WeaponSkin_12',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_3.WeaponSkin_3',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_7.WeaponSkin_7',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_23.WeaponSkin_23',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_14.WeaponSkin_14',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_25.WeaponSkin_25',
  '/Game/Gear/WeaponSkins/_Design/SkinParts/WeaponSkin_2.WeaponSkin_2',
];

export const WEAPON_TRINKETS = [
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_8.WeaponTrinket_8',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_50.WeaponTrinket_50',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_15.WeaponTrinket_15',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_14.WeaponTrinket_14',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_6.WeaponTrinket_6',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_26.WeaponTrinket_26',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_29.WeaponTrinket_29',
  '/Game/PatchDLC/Customizations/Gear/Weapons/WeaponTrinkets/WeaponTrinket_59.WeaponTrinket_59',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_18.WeaponTrinket_18',
  '/Game/PatchDLC/EventVDay/Gear/Weapon/WeaponTrinkets/_Shared/Trinket_League_VDay_1.Trinket_League_VDay_1',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_25.WeaponTrinket_25',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_24.WeaponTrinket_24',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_53.WeaponTrinket_53',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_22.WeaponTrinket_22',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_4.WeaponTrinket_4',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_12.WeaponTrinket_12',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_44.WeaponTrinket_44',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_58.WeaponTrinket_58',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_35.WeaponTrinket_35',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_54.WeaponTrinket_54',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_37.WeaponTrinket_37',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_51.WeaponTrinket_51',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_5.WeaponTrinket_5',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_16.WeaponTrinket_16',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_17.WeaponTrinket_17',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_2.WeaponTrinket_2',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_9.WeaponTrinket_9',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_38.WeaponTrinket_38',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_28.WeaponTrinket_28',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_19.WeaponTrinket_19',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_33.WeaponTrinket_33',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_34.WeaponTrinket_34',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_11.WeaponTrinket_11',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_31.WeaponTrinket_31',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_32.WeaponTrinket_32',
  '/Game/PatchDLC/Dandelion/Gear/WeaponTrinkets/_Shared/Trinket_MercenaryDay_01_CandyCane.Trinket_MercenaryDay_01_CandyCane',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_52.WeaponTrinket_52',
  '/Game/PatchDLC/Hibiscus/Gear/WeaponTrinkets/_Shared/Trinket_Hibiscus_02_Necrocookmicon.Trinket_Hibiscus_02_Necrocookmicon',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_27.WeaponTrinket_27',
  '/Game/PatchDLC/Dandelion/Gear/WeaponTrinkets/_Shared/Trinket_Dandelion_01_JackGoldenMask.Trinket_Dandelion_01_JackGoldenMask',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_41.WeaponTrinket_41',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_39.WeaponTrinket_39',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_42.WeaponTrinket_42',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_48.WeaponTrinket_48',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_3.WeaponTrinket_3',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_30.WeaponTrinket_30',
  '/Game/PatchDLC/BloodyHarvest/Gear/Weapons/WeaponTrinkets/_Shared/Trinket_League_BloodyHarvest_1.Trinket_League_BloodyHarvest_1',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_13.WeaponTrinket_13',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_21.WeaponTrinket_21',
  '/Game/PatchDLC/Dandelion/Gear/WeaponTrinkets/_Shared/Trinket_Dandelion_02_Mimic.Trinket_Dandelion_02_Mimic',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_7.WeaponTrinket_7',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_20.WeaponTrinket_20',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_10.WeaponTrinket_10',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_47.WeaponTrinket_47',
  '/Game/PatchDLC/Hibiscus/Gear/WeaponTrinkets/_Shared/Trinket_Hibiscus_01_Squidly.Trinket_Hibiscus_01_Squidly',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_49.WeaponTrinket_49',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_46.WeaponTrinket_46',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_57.WeaponTrinket_57',
  '/Game/PatchDLC/Steam/Gear/WeaponTrinkets/WeaponTrinket_SteamPunk.WeaponTrinket_SteamPunk',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_45.WeaponTrinket_45',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_43.WeaponTrinket_43',
  '/Game/Gear/WeaponTrinkets/_Design/TrinketParts/WeaponTrinket_40.WeaponTrinket_40',
  '/Game/PatchDLC/Event2/Gear/_Design/WeaponTrinkets/WeaponTrinket_Cartels_1.WeaponTrinket_Cartels_1',
];

export const ROOM_DECORATIONS = [
  '/Game/Pickups/RoomDecoration/RoomDecoration_34.RoomDecoration_34',
  '/Game/Pickups/RoomDecoration/RoomDecoration_35.RoomDecoration_35',
  '/Game/Pickups/RoomDecoration/RoomDecoration_4.RoomDecoration_4',
  '/Game/Pickups/RoomDecoration/RoomDecoration_12.RoomDecoration_12',
  '/Game/Pickups/RoomDecoration/RoomDecoration_13.RoomDecoration_13',
  '/Game/Pickups/RoomDecoration/RoomDecoration_46.RoomDecoration_46',
  '/Game/Pickups/RoomDecoration/RoomDecoration_49.RoomDecoration_49',
  '/Game/Pickups/RoomDecoration/RoomDecoration_51.RoomDecoration_51',
  '/Game/Pickups/RoomDecoration/RoomDecoration_48.RoomDecoration_48',
  '/Game/Pickups/RoomDecoration/RoomDecoration_56.RoomDecoration_56',
  '/Game/Pickups/RoomDecoration/RoomDecoration_57.RoomDecoration_57',
  '/Game/PatchDLC/Dandelion/Customizations/RoomDeco/RoomDeco_DLC1_2.RoomDeco_DLC1_2',
  '/Game/Pickups/RoomDecoration/RoomDecoration_29.RoomDecoration_29',
  '/Game/PatchDLC/Hibiscus/Customizations/RoomDeco/RoomDeco_DLC2_5.RoomDeco_DLC2_5',
  '/Game/Pickups/RoomDecoration/RoomDecoration_43.RoomDecoration_43',
  '/Game/Pickups/RoomDecoration/RoomDecoration_9.RoomDecoration_9',
  '/Game/Pickups/RoomDecoration/RoomDecoration_62.RoomDecoration_62',
  '/Game/Pickups/RoomDecoration/RoomDecoration_61.RoomDecoration_61',
  '/Game/PatchDLC/Hibiscus/Customizations/RoomDeco/RoomDeco_DLC2_8.RoomDeco_DLC2_8',
  '/Game/Pickups/RoomDecoration/RoomDecoration_20.RoomDecoration_20',
  '/Game/Pickups/RoomDecoration/RoomDecoration_21.RoomDecoration_21',
  '/Game/Pickups/RoomDecoration/RoomDecoration_22.RoomDecoration_22',
  '/Game/Pickups/RoomDecoration/RoomDecoration_23.RoomDecoration_23',
  '/Game/Pickups/RoomDecoration/RoomDecoration_24.RoomDecoration_24',
  '/Game/Pickups/RoomDecoration/RoomDecoration_25.RoomDecoration_25',
  '/Game/Pickups/RoomDecoration/RoomDecoration_31.RoomDecoration_31',
  '/Game/PatchDLC/Dandelion/Customizations/RoomDeco/RoomDeco_DLC1_3.RoomDeco_DLC1_3',
  '/Game/Pickups/RoomDecoration/RoomDecoration_42.RoomDecoration_42',
  '/Game/Pickups/RoomDecoration/RoomDecoration_19.RoomDecoration_19',
  '/Game/PatchDLC/Dandelion/Customizations/RoomDeco/RoomDeco_DLC1_6.RoomDeco_DLC1_6',
  '/Game/Pickups/RoomDecoration/RoomDecoration_30.RoomDecoration_30',
  '/Game/PatchDLC/Dandelion/Customizations/RoomDeco/RoomDeco_DLC1_5.RoomDeco_DLC1_5',
  '/Game/Pickups/RoomDecoration/RoomDecoration_15.RoomDecoration_15',
  '/Game/PatchDLC/Hibiscus/Customizations/RoomDeco/RoomDeco_DLC2_4.RoomDeco_DLC2_4',
  '/Game/Pickups/RoomDecoration/RoomDecoration_60.RoomDecoration_60',
  '/Game/Pickups/RoomDecoration/RoomDecoration_11.RoomDecoration_11',
  '/Game/Pickups/RoomDecoration/RoomDecoration_27.RoomDecoration_27',
  '/Game/PatchDLC/Hibiscus/Customizations/RoomDeco/RoomDeco_DLC2_1.RoomDeco_DLC2_1',
  '/Game/Pickups/RoomDecoration/RoomDecoration_16.RoomDecoration_16',
  '/Game/Pickups/RoomDecoration/RoomDecoration_37.RoomDecoration_37',
  '/Game/Pickups/RoomDecoration/RoomDecoration_38.RoomDecoration_38',
  '/Game/Pickups/RoomDecoration/RoomDecoration_39.RoomDecoration_39',
  '/Game/Pickups/RoomDecoration/RoomDecoration_58.RoomDecoration_58',
  '/Game/Pickups/RoomDecoration/RoomDecoration_44.RoomDecoration_44',
  '/Game/Pickups/RoomDecoration/RoomDecoration_5.RoomDecoration_5',
  '/Game/Pickups/RoomDecoration/RoomDecoration_52.RoomDecoration_52',
  '/Game/Pickups/RoomDecoration/RoomDecoration_55.RoomDecoration_55',
  '/Game/PatchDLC/Dandelion/Customizations/RoomDeco/RoomDeco_DLC1_1.RoomDeco_DLC1_1',
  '/Game/Pickups/RoomDecoration/RoomDecoration_6.RoomDecoration_6',
  '/Game/PatchDLC/Hibiscus/Customizations/RoomDeco/RoomDeco_DLC2_2.RoomDeco_DLC2_2',
  '/Game/Pickups/RoomDecoration/RoomDecoration_50.RoomDecoration_50',
  '/Game/Pickups/RoomDecoration/RoomDecoration_47.RoomDecoration_47',
  '/Game/Pickups/RoomDecoration/RoomDecoration_33.RoomDecoration_33',
  '/Game/Pickups/RoomDecoration/RoomDecoration_45.RoomDecoration_45',
  '/Game/Pickups/RoomDecoration/RoomDecoration_41.RoomDecoration_41',
  '/Game/Pickups/RoomDecoration/RoomDecoration_18.RoomDecoration_18',
  '/Game/PatchDLC/Dandelion/Customizations/RoomDeco/RoomDeco_DLC1_4.RoomDeco_DLC1_4',
  '/Game/Pickups/RoomDecoration/RoomDecoration_40.RoomDecoration_40',
  '/Game/Pickups/RoomDecoration/RoomDecoration_36.RoomDecoration_36',
  '/Game/Pickups/RoomDecoration/RoomDecoration_10.RoomDecoration_10',
  '/Game/Pickups/RoomDecoration/RoomDecoration_28.RoomDecoration_28',
  '/Game/PatchDLC/Hibiscus/Customizations/RoomDeco/RoomDeco_DLC2_6.RoomDeco_DLC2_6',
  '/Game/Pickups/RoomDecoration/RoomDecoration_65.RoomDecoration_65',
  '/Game/PatchDLC/Hibiscus/Customizations/RoomDeco/RoomDeco_DLC2_3.RoomDeco_DLC2_3',
  '/Game/Pickups/RoomDecoration/RoomDecoration_32.RoomDecoration_32',
  '/Game/Pickups/RoomDecoration/RoomDecoration_66.RoomDecoration_66',
  '/Game/Pickups/RoomDecoration/RoomDecoration_64.RoomDecoration_64',
  '/Game/Pickups/RoomDecoration/RoomDecoration_17.RoomDecoration_17',
  '/Game/Pickups/RoomDecoration/RoomDecoration_7.RoomDecoration_7',
  '/Game/Pickups/RoomDecoration/RoomDecoration_8.RoomDecoration_8',
  '/Game/Pickups/RoomDecoration/RoomDecoration_67.RoomDecoration_67',
  '/Game/Pickups/RoomDecoration/RoomDecoration_26.RoomDecoration_26',
  '/Game/PatchDLC/Hibiscus/Customizations/RoomDeco/RoomDeco_DLC2_7.RoomDeco_DLC2_7',
  '/Game/Pickups/RoomDecoration/RoomDecoration_59.RoomDecoration_59',
  '/Game/Pickups/RoomDecoration/RoomDecoration_63.RoomDecoration_63',
  '/Game/PatchDLC/Event2/Pickups/RoomDecoration/RoomDecoration_Event2_3.RoomDecoration_Event2_3',
];

export const VEHICLE_CHASSIS = [
  '/Game/Vehicles/Outrunner/Design/WT_Outrunner_BuggyWheels.WT_Outrunner_BuggyWheels',
  '/Game/Vehicles/Outrunner/Design/WT_Outrunner_HoverWheels.WT_Outrunner_HoverWheels',
  '/Game/Vehicles/Outrunner/Design/WT_Outrunner_TwitchyWheels.WT_Outrunner_TwitchyWheels',
  '/Game/Vehicles/Outrunner/Design/WT_Outrunner_ZipWheels.WT_Outrunner_ZipWheels',
  '/Game/Vehicles/Technical/Design/WT_Technical_AllTerrainWheels.WT_Technical_AllTerrainWheels',
  '/Game/Vehicles/Technical/Design/WT_Technical_BarbedWheels.WT_Technical_BarbedWheels',
  '/Game/Vehicles/Technical/Design/WT_Technical_HoverWheels.WT_Technical_HoverWheels',
  '/Game/Vehicles/Technical/Design/WT_Technical_MonsterWheels.WT_Technical_MonsterWheels',
  '/Game/Vehicles/Revolver/Design/WT_Revolver_DualWheel.WT_Revolver_DualWheel',
  '/Game/Vehicles/Revolver/Design/WT_Revolver_HoverWheel.WT_Revolver_HoverWheel',
  '/Game/Vehicles/Revolver/Design/WT_Revolver_MonoWheel.WT_Revolver_MonoWheel',
  '/Game/Vehicles/Revolver/Design/WT_Revolver_WIdeWheel.WT_Revolver_WIdeWheel',
];

export const VEHICLE_PARTS = [
  '/Game/Vehicles/Outrunner/Design/Parts/Armor/VehiclePart_Outrunner_Armor_BasicArmor.VehiclePart_Outrunner_Armor_BasicArmor',
  '/Game/Vehicles/Outrunner/Design/Parts/Armor/VehiclePart_Outrunner_Armor_HeavyArmor.VehiclePart_Outrunner_Armor_HeavyArmor',
  '/Game/Vehicles/Outrunner/Design/Parts/CoreMod/BlazeBooster/VehiclePart_CoreMod_BlazeBooster.VehiclePart_CoreMod_BlazeBooster',
  '/Game/Vehicles/Outrunner/Design/Parts/CoreMod/BoostCanisters/VehiclePart_CoreMod_BoostCanisters.VehiclePart_CoreMod_BoostCanisters',
  '/Game/Vehicles/Outrunner/Design/Parts/CoreMod/EnergyCells/VehiclePart_CoreMod_EnergyCells.VehiclePart_CoreMod_EnergyCells',
  '/Game/Vehicles/Outrunner/Design/Parts/CoreMod/RazerWings/VehiclePart_CoreMod_RazerWings.VehiclePart_CoreMod_RazerWings',
  '/Game/Vehicles/VehicleWeapons/DriverWeapons/Type_FlameThrower/FlameThrower/VehiclePart_WeaponDriver_FlameThrower_Native.VehiclePart_WeaponDriver_FlameThrower_Native',
  '/Game/Vehicles/VehicleWeapons/DriverWeapons/Type_FlameThrower/TeslaCoil/VehiclePart_WeaponDriver_TeslaCoil_Native.VehiclePart_WeaponDriver_TeslaCoil_Native',
  '/Game/Vehicles/VehicleWeapons/DriverWeapons/Type_MachineGun/OutrunnerMachineGun/VehiclePart_WeaponDriver_OutrunnerMachineGun_Native.VehiclePart_WeaponDriver_OutrunnerMachineGun_Native',
  '/Game/Vehicles/VehicleWeapons/GunnerWeapons/Type_MissileLauncher/HeavyMissile/VehiclePart_Weapon_HeavyMissile_Native.VehiclePart_Weapon_HeavyMissile_Native',
  '/Game/Vehicles/VehicleWeapons/GunnerWeapons/Type_MissileLauncher/ShotgunMissile/VehiclePart_Weapon_ShotgunMissile_Native.VehiclePart_Weapon_ShotgunMissile_Native',
  '/Game/Vehicles/VehicleWeapons/GunnerWeapons/Type_MissileLauncher/SwarmerMissile/VehiclePart_Weapon_SwarmerMissile_Native.VehiclePart_Weapon_SwarmerMissile_Native',

  '/Game/Vehicles/Technical/Design/Parts/Accessory/FlatBed/VehiclePart_CoreMod_Flatbed.VehiclePart_CoreMod_Flatbed',
  '/Game/Vehicles/Technical/Design/Parts/Accessory/FuelBarrels/VehiclePart_CoreMod_FuelBarrels.VehiclePart_CoreMod_FuelBarrels',
  '/Game/Vehicles/Technical/Design/Parts/Accessory/JetBooster/VehiclePart_CoreMod_JetBooster.VehiclePart_CoreMod_JetBooster',
  '/Game/Vehicles/Technical/Design/Parts/Accessory/ToxicBooster/VehiclePart_CoreMod_ToxicBooster.VehiclePart_CoreMod_ToxicBooster',
  '/Game/Vehicles/Technical/Design/Parts/Armor/VehiclePart_Techincal_Armor_BasicArmor.VehiclePart_Techincal_Armor_BasicArmor',
  '/Game/Vehicles/Technical/Design/Parts/Armor/VehiclePart_Technical_Armor_HeavyArmor.VehiclePart_Technical_Armor_HeavyArmor',
  '/Game/Vehicles/Technical/Design/Parts/Armor/VehiclePart_Technical_Armor_MeatGrinder.VehiclePart_Technical_Armor_MeatGrinder',
  '/Game/Vehicles/VehicleWeapons/DriverWeapons/Type_MachineGun/FlakCannon/VehiclePart_WeaponDriver_FlakCannon_Native.VehiclePart_WeaponDriver_FlakCannon_Native',
  '/Game/Vehicles/VehicleWeapons/DriverWeapons/Type_MachineGun/MachineGun/VehiclePart_WeaponDriver_MachineGun_Native.VehiclePart_WeaponDriver_MachineGun_Native',
  '/Game/Vehicles/VehicleWeapons/GunnerWeapons/Type_Catapult/BarrelLauncher/VehiclePart_Weapon_BarrelLauncher_Native.VehiclePart_Weapon_BarrelLauncher_Native',
  '/Game/Vehicles/VehicleWeapons/GunnerWeapons/Type_Catapult/PropelledBombsLauncher/VehiclePart_Weapon_PropelledBombsLauncher_Native.VehiclePart_Weapon_PropelledBombsLauncher_Native',
  '/Game/Vehicles/VehicleWeapons/GunnerWeapons/Type_Catapult/StickyBombLauncher/VehiclePart_Weapon_StickyBombs_Native.VehiclePart_Weapon_StickyBombs_Native',

  '/Game/Vehicles/Revolver/Design/Parts/Armor/VehiclePart_Revolver_Armor_BasicArmor.VehiclePart_Revolver_Armor_BasicArmor',
  '/Game/Vehicles/Revolver/Design/Parts/Armor/VehiclePart_Revolver_Armor_HeavyArmor.VehiclePart_Revolver_Armor_HeavyArmor',
  '/Game/Vehicles/Revolver/Design/Parts/CoreMod/CryoBooster/VehiclePart_CryoBooster.VehiclePart_CryoBooster',
  '/Game/Vehicles/Revolver/Design/Parts/CoreMod/DigiThruster/VehiclePart_DigiThruster.VehiclePart_DigiThruster',
  '/Game/Vehicles/Revolver/Design/Parts/CoreMod/Firestarter/VehiclePart_FireStarter.VehiclePart_FireStarter',
  '/Game/Vehicles/Revolver/Design/Parts/CoreMod/HeavyBooster/VehiclePart_HeavyBooster.VehiclePart_HeavyBooster',
  '/Game/Vehicles/VehicleWeapons/DriverWeapons/Type_MechanicalLauncher/BlazeRodLancer/VehiclePart_WeaponDriver_BlazeRodLauncher_Native.VehiclePart_WeaponDriver_BlazeRodLauncher_Native',
  '/Game/Vehicles/VehicleWeapons/DriverWeapons/Type_MechanicalLauncher/RevolverMachineGun/VehiclePart_WeaponDriver_RevolverMachineGun_Native.VehiclePart_WeaponDriver_RevolverMachineGun_Native',
  '/Game/Vehicles/VehicleWeapons/DriverWeapons/Type_MechanicalLauncher/SawBladeLancer/VehiclePart_WeaponDriver_SawBladeLauncher_Native.VehiclePart_WeaponDriver_SawBladeLauncher_Native',
];

export const VEHICLE_SKINS = [
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Atlas.VehiclePart_Mat_VehiclePart_Outrunner_Atlas',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Batmobile.VehiclePart_Mat_VehiclePart_Outrunner_Batmobile',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_COV.VehiclePart_Mat_VehiclePart_Outrunner_COV',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Dahl.VehiclePart_Mat_VehiclePart_Outrunner_Dahl',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Default.VehiclePart_Mat_VehiclePart_Outrunner_Default',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Ellie1.VehiclePart_Mat_VehiclePart_Outrunner_Ellie1',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_FF.VehiclePart_Mat_VehiclePart_Outrunner_FF',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Fire.VehiclePart_Mat_VehiclePart_Outrunner_Fire',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Forest.VehiclePart_Mat_VehiclePart_Outrunner_Forest',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_GBX.VehiclePart_Mat_VehiclePart_Outrunner_GBX',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Gold.VehiclePart_Mat_VehiclePart_Outrunner_Gold',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Grog.VehiclePart_Mat_VehiclePart_Outrunner_Grog',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Gulf.VehiclePart_Mat_VehiclePart_Outrunner_Gulf',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Herbie.VehiclePart_Mat_VehiclePart_Outrunner_Herbie',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Hexagon.VehiclePart_Mat_VehiclePart_Outrunner_Hexagon',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Houndstooth.VehiclePart_Mat_VehiclePart_Outrunner_Houndstooth',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_HubbaBubba.VehiclePart_Mat_VehiclePart_Outrunner_HubbaBubba',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Hyp.VehiclePart_Mat_VehiclePart_Outrunner_Hyp',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Hyp2.VehiclePart_Mat_VehiclePart_Outrunner_Hyp2',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Infection.VehiclePart_Mat_VehiclePart_Outrunner_Infection',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Jakobs.VehiclePart_Mat_VehiclePart_Outrunner_Jakobs',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Maliwan.VehiclePart_Mat_VehiclePart_Outrunner_Maliwan',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Maya.VehiclePart_Mat_VehiclePart_Outrunner_Maya',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Pirate.VehiclePart_Mat_VehiclePart_Outrunner_Pirate',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Prisa.VehiclePart_Mat_VehiclePart_Outrunner_Prisa',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_RedMachine.VehiclePart_Mat_VehiclePart_Outrunner_RedMachine',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_SDCC.VehiclePart_Mat_VehiclePart_Outrunner_SDCC',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Stealth.VehiclePart_Mat_VehiclePart_Outrunner_Stealth',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Torgue.VehiclePart_Mat_VehiclePart_Outrunner_Torgue',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Tri.VehiclePart_Mat_VehiclePart_Outrunner_Tri',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Vladof.VehiclePart_Mat_VehiclePart_Outrunner_Vladof',
  '/Game/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Wrap.VehiclePart_Mat_VehiclePart_Outrunner_Wrap',
  '/Game/PatchDLC/Hibiscus/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Fish.VehiclePart_Mat_VehiclePart_Outrunner_Fish',
  '/Game/PatchDLC/Hibiscus/Vehicles/Outrunner/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Outrunner_Tentacle.VehiclePart_Mat_VehiclePart_Outrunner_Tentacle',

  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Atlas.VehiclePart_Mat_VehiclePart_Technical_Atlas',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Bling.VehiclePart_Mat_VehiclePart_Technical_Bling',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_BlueAngel.VehiclePart_Mat_VehiclePart_Technical_BlueAngel',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Bubblegum.VehiclePart_Mat_VehiclePart_Technical_Bubblegum',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Camo.VehiclePart_Mat_VehiclePart_Technical_Camo',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Checker.VehiclePart_Mat_VehiclePart_Technical_Checker',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Cov.VehiclePart_Mat_VehiclePart_Technical_Cov',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Dahl.VehiclePart_Mat_VehiclePart_Technical_Dahl',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Default.VehiclePart_Mat_VehiclePart_Technical_Default',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Dino.VehiclePart_Mat_VehiclePart_Technical_Dino',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_E3.VehiclePart_Mat_VehiclePart_Technical_E3',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Ellie1.VehiclePart_Mat_VehiclePart_Technical_Ellie1',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Festi.VehiclePart_Mat_VehiclePart_Technical_Festi',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Forest.VehiclePart_Mat_VehiclePart_Technical_Forest',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_GBX.VehiclePart_Mat_VehiclePart_Technical_GBX',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_GoldenTicket.VehiclePart_Mat_VehiclePart_Technical_GoldenTicket',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_HYP.VehiclePart_Mat_VehiclePart_Technical_HYP',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Halftone.VehiclePart_Mat_VehiclePart_Technical_Halftone',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_JAK.VehiclePart_Mat_VehiclePart_Technical_JAK',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_MAL.VehiclePart_Mat_VehiclePart_Technical_MAL',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Maya.VehiclePart_Mat_VehiclePart_Technical_Maya',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Plaid.VehiclePart_Mat_VehiclePart_Technical_Plaid',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Roadkill.VehiclePart_Mat_VehiclePart_Technical_Roadkill',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Sand.VehiclePart_Mat_VehiclePart_Technical_Sand',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Skag.VehiclePart_Mat_VehiclePart_Technical_Skag',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Stealth.VehiclePart_Mat_VehiclePart_Technical_Stealth',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Thunderbird.VehiclePart_Mat_VehiclePart_Technical_Thunderbird',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Torgue.VehiclePart_Mat_VehiclePart_Technical_Torgue',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Vaughn.VehiclePart_Mat_VehiclePart_Technical_Vaughn',
  '/Game/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Vladof.VehiclePart_Mat_VehiclePart_Technical_Vladof',
  '/Game/PatchDLC/Hibiscus/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Tentacle.VehiclePart_Mat_VehiclePart_Technical_Tentacle',
  '/Game/PatchDLC/Hibiscus/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Fish.VehiclePart_Mat_VehiclePart_Technical_Fish',
  '/Game/PatchDLC/Hibiscus/Vehicles/Technical/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Technical_Frost.VehiclePart_Mat_VehiclePart_Technical_Frost',

  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Atlas.VehiclePart_Mat_VehiclePart_Revolver_Atlas',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_COV.VehiclePart_Mat_VehiclePart_Revolver_COV',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Chopper.VehiclePart_Mat_VehiclePart_Revolver_Chopper',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Chups.VehiclePart_Mat_VehiclePart_Revolver_Chups',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Dahl.VehiclePart_Mat_VehiclePart_Revolver_Dahl',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Dark.VehiclePart_Mat_VehiclePart_Revolver_Dark',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Default.VehiclePart_Mat_VehiclePart_Revolver_Default',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Ellie1.VehiclePart_Mat_VehiclePart_Revolver_Ellie1',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Forest.VehiclePart_Mat_VehiclePart_Revolver_Forest',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_GBX.VehiclePart_Mat_VehiclePart_Revolver_GBX',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_GC.VehiclePart_Mat_VehiclePart_Revolver_GC',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_HubbaBubba.VehiclePart_Mat_VehiclePart_Revolver_HubbaBubba',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Hyp.VehiclePart_Mat_VehiclePart_Revolver_Hyp',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Hyp2.VehiclePart_Mat_VehiclePart_Revolver_Hyp2',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Jakobs.VehiclePart_Mat_VehiclePart_Revolver_Jakobs',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_LifeSaver.VehiclePart_Mat_VehiclePart_Revolver_LifeSaver',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Maliwan.VehiclePart_Mat_VehiclePart_Revolver_Maliwan',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Mask.VehiclePart_Mat_VehiclePart_Revolver_Mask',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Maya.VehiclePart_Mat_VehiclePart_Revolver_Maya',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Ninja.VehiclePart_Mat_VehiclePart_Revolver_Ninja',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Pepto.VehiclePart_Mat_VehiclePart_Revolver_Pepto',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Police.VehiclePart_Mat_VehiclePart_Revolver_Police',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Stealth.VehiclePart_Mat_VehiclePart_Revolver_Stealth',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Torgue.VehiclePart_Mat_VehiclePart_Revolver_Torgue',
  '/Game/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Vladof.VehiclePart_Mat_VehiclePart_Revolver_Vladof',
  '/Game/PatchDLC/Hibiscus/Vehicles/Revolver/Design/Parts/Materials/VehiclePart_Mat_VehiclePart_Revolver_Fish.VehiclePart_Mat_VehiclePart_Revolver_Fish',
];

export function getExpForLevel(level: number): number {
  return expValues[level - 1];
}

export function getLevelForExp(exp: number): number {
  for (let i = 0; i < maxLevel; i++) {
    if (exp < expValues[i]) {
      return i;
    }
  }
  return maxLevel;
}

@Pipe({ name: 'level' })
export class ExpToLevelPipe implements PipeTransform {
  public transform(value: number, ...args: []): any {
    return getLevelForExp(value);
  }
}
